# Generated by Django 2.1.7 on 2019-04-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpic',
            name='before',
            field=models.ImageField(upload_to='dataset/inpic/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='outpic',
            name='after',
            field=models.ImageField(upload_to='dataset/outpic/%Y/%m/%d/'),
        ),
    ]
