# Generated by Django 2.1.7 on 2019-06-14 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picxi', '0002_auto_20190422_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegPic',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='picxi.GUIDModel')),
                ('ing', models.ImageField(upload_to='dataset/segpic/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('origin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inpic', to='picxi.InPic')),
            ],
            bases=('picxi.guidmodel',),
        ),
        migrations.AlterField(
            model_name='outpic',
            name='origin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picxi.SegPic'),
        ),
    ]
