# Generated by Django 2.1.7 on 2019-06-14 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picxi', '0003_auto_20190614_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segpic',
            name='guidmodel_ptr',
        ),
        migrations.RemoveField(
            model_name='segpic',
            name='origin_id',
        ),
        migrations.AddField(
            model_name='inpic',
            name='color_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inpic',
            name='ing',
            field=models.ImageField(blank=True, null=True, upload_to='dataset/segpic/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='inpic',
            name='before',
            field=models.ImageField(blank=True, null=True, upload_to='dataset/inpic/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='outpic',
            name='after',
            field=models.ImageField(blank=True, null=True, upload_to='dataset/outpic/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='outpic',
            name='origin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='picxi.InPic'),
        ),
        migrations.DeleteModel(
            name='SegPic',
        ),
    ]
