# Generated by Django 2.1.7 on 2019-06-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picxi', '0004_auto_20190614_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegPic',
            fields=[
                ('guidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='picxi.GUIDModel')),
                ('ing', models.ImageField(blank=True, null=True, upload_to='dataset/segpic/%Y/%m/%d/')),
                ('color_list', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('picxi.guidmodel',),
        ),
        migrations.RemoveField(
            model_name='inpic',
            name='ing',
        ),
        migrations.RemoveField(
            model_name='outpic',
            name='origin_id',
        ),
        migrations.AddField(
            model_name='segpic',
            name='in_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_id', to='picxi.InPic'),
        ),
        migrations.AddField(
            model_name='outpic',
            name='seg_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_id', to='picxi.SegPic'),
        ),
    ]
