# Generated by Django 2.1.7 on 2019-06-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picxi', '0005_auto_20190614_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inpic',
            name='color_list',
        ),
    ]
