# Generated by Django 2.1.7 on 2019-06-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picxi', '0006_remove_inpic_color_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outpic',
            name='seg_id',
        ),
    ]
