# Generated by Django 2.1.7 on 2019-07-15 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picxi', '0007_remove_outpic_seg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpic',
            name='seg_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seg_id', to='picxi.InPic'),
        ),
    ]
