from config.util import get_server_info_value
from .base import *

SETTING_PRD_DIC = get_server_info_value("deployment")
SECRET_KEY = SETTING_PRD_DIC["SECRET_KEY"]

DEBUG = False

ALLOWED_HOSTS = [
    "127.0.0.1",
    '.compute.amazonaws.com'
            ]

DATABASES = {
    'default': SETTING_PRD_DIC['DATABASES']["default"]
}
AWS_ACCESS_KEY_ID = SETTING_PRD_DIC["AWS_ACCESS_KEY_ID"]
AWS_SECRET_ACCESS_KEY = SETTING_PRD_DIC["AWS_SECRET_ACCESS_KEY"]
AWS_REGION = SETTING_PRD_DIC["AWS_REGION"]
AWS_STORAGE_BUCKET_NAME = SETTING_PRD_DIC["AWS_STORAGE_BUCKET_NAME"]
AWS_S3_CUSTOM_DOMAIN = SETTING_PRD_DIC["AWS_S3_CUSTOM_DOMAIN"]
AWS_S3_OBJECT_PARAMETERS = SETTING_PRD_DIC["AWS_S3_OBJECT_PARAMETERS"]
AWS_DEFAULT_ACL = SETTING_PRD_DIC["AWS_DEFAULT_ACL"]
AWS_LOCATION = SETTING_PRD_DIC["AWS_LOCATION"]

STATIC_URL = 'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static')
]
DEFAULT_FILE_STORAGE = 'config.asset_storage.MediaStorage'

CORS_ORIGIN_WHITELIST = (
    'localhost:3000/'
)
